[tool.poetry]
name = "exquisitor"
version = "0.1.0"
description = ""
authors = ["Patryk Filip Gryz <pfgryz@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
psutil = "^6.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
